### ISSUE TITLE
Communication Rules for initial installation/setup

### ISSUE THREAD

**Issue by Teckfahimkanji** [MicrosoftDocs/data-integration#124]
Hi There,

Context: I'm working with our infrastructure team to prove out an installation of the on-premise data gateway on a VM inside azure to serve as a hub for reports to access all private databases we host in our Azure tenant (Power BI service cannot access them as they have no public endpoints and the VNET Gateways are in Preview mode so we are looking at the on-premise data gateway as an interim solution).  No network communication is permitted outside of the specifications in this article and we are not able to configure the gateway.

When I run the software and try to sign-in to register the gateway I get all sorts of network/firewall/tls/healthcheck failures ... I think the document needs to be revised to scope the description of the configuration to "post-installation" or updated to include additional commentary and rules specifications regarding installation and the specific rules therein.

I'm still working with our infrastructure team to try to figure out how to get this to work but creating a landing zone and configuring a vnet with the rules you specified is insufficient (thus far).

Happy to show you screenshots and logs files of our issues if that helps you get a better idea about what the issue is and whether it's related to this document or not.

Cheers,

Fahim Kanji
Fahim.Kanji@teck.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4daef9a-341c-696a-1d19-de05ffd67588
* Version Independent ID: 7cd18c28-7227-488a-aa28-6b869058e715
* Content: [Adjust communication settings for the on-premises data gateway](https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-communication)
* Content Source: [data-integration/gateway/service-gateway-communication.md](https://github.com/MicrosoftDocs/data-integration/blob/main/data-integration/gateway/service-gateway-communication.md)
* Product: **on-premises-data-gateway**
* Technology: ****
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by Teckfahimkanji** [comment]
![image](https://user-images.githubusercontent.com/83241428/148428628-8cf61917-492a-4c64-834f-b4a6ca8a1c15.png)
EnterpriseGatewayConfigurator.exe Information: 0 : GetDataDirectory: 'C:\Users\PBIEgwService\AppData\Local\Microsoft\On-premises data gateway'
EnterpriseGatewayConfigurator.exe Information: 0 : Sign In
EnterpriseGatewayConfigurator.exe Error: 0 : Exception: Microsoft.PowerBI.DataMovement.GatewayCommon.EmailDiscoveryServiceException: Network request returned unexpected error. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.DataMovement.GatewayCommon.ConfiguratorClientExtensions.<DiscoverEmailProperties>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.PowerBI.DataMovement.GatewayCommon.ServiceEnvironmentDetailsFactory.GetEnvironment(String emailAddress, Uri endpoint, String preferredCloud)
   at Microsoft.PowerBI.DataMovement.GatewayUiCommon.WizardSignInViewModel.StartSignIn(IServiceEnvironmentDetailsFactory serviceEnvironmentDetailsFactory, ConfiguratorAzureGeo selectedGeo)
   at Microsoft.PowerBI.DataMovement.GatewayUiCommon.WizardSignInViewModel.DoNext(Object param)
   at Microsoft.PowerBI.DataMovement.GatewayUiCommon.WizardViewModelBase.DoNextWorker(Object param)
   at Microsoft.PowerBI.DataMovement.GatewayUiCommon.RelayCommand.<>c__DisplayClass19_0.<Execute>b__0()
EnterpriseGatewayConfigurator.exe Information: 0 : Update checks
EnterpriseGatewayConfigurator.exe Information: 0 : Create web request for Uri: http://www.msftncsi.com/ncsi.txt
EnterpriseGatewayConfigurator.exe Information: 0 : Create httpClient request for Uri: http://www.msftncsi.com/ncsi.txt
EnterpriseGatewayConfigurator.exe Information: 0 : Response status: 470
EnterpriseGatewayConfigurator.exe Information: 0 : Checking for PbiEgwService
EnterpriseGatewayConfigurator.exe Information: 0 : Fetch state for PbiEgwService
EnterpriseGatewayConfigurator.exe Information: 0 : Service state: Running
EnterpriseGatewayConfigurator.exe Error: 0 : Gateway service health check Network failed with error : System.Net.WebException: The remote server returned an error: (470) status code 470.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.PowerBI.DataMovement.Pipeline.GatewayCore.HealthCheck.NetworkCheck.WebRequestCheck()
   at Microsoft.PowerBI.DataMovement.Pipeline.GatewayCore.HealthCheck.NetworkCheck.<>c.<Run>b__5_0()
   at Microsoft.PowerBI.DataMovement.Pipeline.GatewayCore.HealthCheck.HealthCheckAction.Run(Func`1 checkMethod)
EnterpriseGatewayConfigurator.exe Information: 0 : Create httpclient request for Uri: http://www.msftncsi.com/ncsi.txt
EnterpriseGatewayConfigurator.exe Information: 0 : Response status: 470

**Comment by JasonWHowell** [comment]
@Teckfahimkanji thanks for the added context and information. For privacy reasons, it would be best if you work with support to report the details of the issues you faced while setting up that environment. If it's already too far gone, I understand its not worth your time.  

I recommend that you edit your post and remove any personal information (email) to avoid over-sharing on the net. 
Thanks, Jason
